export const user = {
  LOAD_LOCAL_OPENID: 'LOAD_LOCAL_OPENID',
  SET_WXSHARE: 'SET_WXSHARE',
  SET_OPENID: 'SET_OPENID',
  // CREATE_CARD: 'CREATE_CARD',
  //
  CHECK_SUBMIT: 'CHECK_SUBMIT',
  //顾问列表
  GET_COUNSELOR: 'GET_COUNSELOR',
  SET_COUNSELOR: 'SET_COUNSELOR',
  //问题列表
  GET_QUESTION: 'GET_QUESTION',
  SET_QUESTION: 'SET_QUESTION',
  //
  ACTION_POST_DATA: 'ACTION_POST_DATA'
}
